name: flutter_walle
description: Get channel information (by meituan walle) from within the Flutter application.
version: 1.0.04
homepage: https://github.com/zileyuan/flutter_walle

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.github.zileyuan.flutter_walle
        pluginClass: FlutterWallePlugin
      ios:
        pluginClass: FlutterWallePlugin
